name: main_project
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^0.13.3
 # image_picker: ^1.1.2
  image_picker: ^0.8.5+3 # Check for the latest version compatible with mobile
  image_picker_web: ^4.0.0  # For web use
  universal_io: ^2.0.4
  flutter_sound: ^9.2.13
  permission_handler: ^11.0.1
  path_provider: ^2.1.2
  #image_picker_web: any
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  shared_preferences: ^2.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/google_icon.png
    - assets/login_illustration.jpg
